version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8088
    volumes:
      - .:/code
    ports:
      - "8088:8088"
    depends_on:
      - db