# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0002_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='modification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
